name: python-sdk

on:
  push:
    branches:
      - '**'


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-bindings:
    name: Test python SDK bindings
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --tag ci_rust_$GITHUB_SHA -f ci/Dockerfile

      - name: Run tests
        run: |
            docker run --rm -v ${{ github.workspace }}:/src -v /mnt/jenkins/python-sdk-ci-test:/root/Documents/cepton w ci_rust_$GITHUB_SHA bash -ex -c '
            cd /app
            python3 -m unittest discover -s tests
            '
